
server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.188.192
    port: 6379
    password: root
  session:
    store-type: redis #session存储方式
    timeout: 1800     #session过期时间 单位：秒